swagger: '2.0'
info:
  version: '1.0'
  title: "TaskManagement"
  description: Task Management è un servizio che permette la gestione e 
l'assegnamento di esami (ovvero gruppi di esercizi) a studenti. Questi 
unltimi dovranno completare gli esercizi. Dopo una deadline definita dal 
T.A. che ha creato l'esame, gli stuenti riceveranno esercizi svolti da 
altri studenti che dovranno correggere. Infine il T.A. darà un voto per 
ogni esercizio e per l'esame ad ogni studente

host: task-management-solo-numeri-0.herokuapp.com 
basePath: /v1
schemes: 
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
        404:
          description: Not found.
    post:
      summary: Create a new user.
      description: Optional extended description in Markdown.
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
	  description: Elaboration without creation.
        201:
          description: Resource created.
        204:
          description: No content.
        400:
          description: Bad Request.
  /exams:
    post:
      summary: Create a new exam.
      description: Optional extended description in Markdown.
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses: 
        200:
          description: OK
        201:
          description: Resource created.
        204:
          description: No content.
        400:
          description: Bad request.
  /exams/{id}:
    get:
      summary: "Get information about a specific exam"
      description: "Return the exam {id}"
      produces:
      - "application/json"
      responses: 
        200:
          description: "ID Found"
        400:
          description: "Invalid ID"
    put:
      summary: "Update exam informations"
      description: "Update exam informations: title and tasks list"
      responses:
        200:
          description: "ID found. Exam updated"
        400:
          description: "Invalid exam ID"
    delete:
      summary: "Delete exam"
      description: "Delete specified exam"
      responses:
        200:
          description: "ID found. Exam deleted"
        400:
          description: "Invalid exam ID"